upstream frontend_local {
    server trading_frontend:3000;
}

upstream backend_local {
    server trading_backend:8000;
}

server {
    listen 80;
    server_name localhost;

    location /api/ {
        proxy_pass http://backend_local/api/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://frontend_local;
        proxy_set_header Host $host;
    }
}
